

 import 'model/question/category_model.dart';
import 'model/question/subcategory.dart';

List<CategoryModel> categories =[
  CategoryModel(isActive: true,name: 'Definitions', type: 'category1',subcategory: null),
  CategoryModel(isActive: true, name: 'Administration', type: 'category2',subcategory: null),
  CategoryModel(isActive: true, name: 'Supply', type: 'category3',subcategory:null),
  CategoryModel(isActive: true, name: 'Composite And Mixed Supply', type: 'category4',subcategory: null),
  CategoryModel(isActive: true, name: 'Leavy And Collection', type: 'category5',subcategory: null),
  CategoryModel(isActive: true, name: 'Composition Scheme', type: 'category6',subcategory: 
  [
    SubCategory(isActive: true, name: 'Intimation', type: 'category6'),
    SubCategory(isActive: true, name: 'Effective date for scheme', type: 'category6'), 
    SubCategory(isActive: true, name: 'Conditions and Restrictions', type: 'category6'),
    SubCategory(isActive: true, name: 'Validity', type: 'category6'),
    SubCategory(isActive: true, name: 'Rate of tax', type: 'category6')

  ]),
  CategoryModel(isActive: true, name: 'Excemptions', type: 'category7',subcategory: null),
  CategoryModel(isActive: true, name: 'Time Of Supply', type: 'category8',subcategory: [
    SubCategory(isActive: true, name: 'Time Of Supply(Goods)', type:'category8', ),
    SubCategory(isActive: true, name: 'Time Of Supply(Services)', type:'category8', ),
    SubCategory(isActive: true, name: 'Time Of Supply(Change in rate of tax)', type:'category8', ),
  ] ),
  CategoryModel(isActive: true, name: 'Valuation', type: 'category9',subcategory: null),
  CategoryModel(isActive: true, name: 'Input Tax Credit', type: 'category10',subcategory: 
  [
    SubCategory(isActive: true, name: 'Eligibility And Condition(ITC)', type: 'category10'),
    SubCategory(isActive: true, name: 'Apportionment of credit and Blocked ITC', type: 'category10'),
    SubCategory(isActive: true, name: 'ITC(special Circumstances)', type: 'category10'),
    SubCategory(isActive: true, name: 'ITC-job work', type: 'category10'),
    SubCategory(isActive: true, name: 'Input service distributor', type: 'category10'),
    SubCategory(isActive: true, name: 'Recovery of excess distributed credit', type: 'category10'),
  ]),
  CategoryModel(isActive: true, name: 'Job Work', type: 'category11',subcategory: null),
  CategoryModel(isActive: true, name: 'Input Service Distributor', type: 'category12',subcategory: null),
  CategoryModel(isActive: true, name: 'Registration', type: 'category13',subcategory: [
    SubCategory(isActive: true, name: 'Liable for registration', type:'category13', ),
    SubCategory(isActive: true, name: 'Compulsory registration', type:'category13', ),
    SubCategory(isActive: true, name: 'Deemed registration', type:'category13', ),
    SubCategory(isActive: true, name: 'Procedure', type:'category13', ),
    SubCategory(isActive: true, name: 'Casual Taxable person & NRTP', type:'category13', ),
    SubCategory(isActive: true, name: 'Amendment', type:'category13', ),
    SubCategory(isActive: true, name: 'Cancellation/Suspention', type:'category13', ),
    SubCategory(isActive: true, name: 'Revocation of Cancellation', type:'category13', ),
    SubCategory(isActive: true, name: 'Suo-Motu Registration', type:'category13', ),
    SubCategory(isActive: true, name: 'UIN to special entities', type:'category13', ),

  ]),
  CategoryModel(isActive: true,name: 'Tax Invoice', type: 'category14',subcategory: [
    SubCategory(isActive: true, name: 'Digital payment to recipient', type:'category14', ),
    SubCategory(isActive: true, name: 'Prohibition-Unauthorized collection of tax', type:'category14', ),
    SubCategory(isActive: true, name: 'indication of tax amount in tax invoice', type:'category14', ),
    SubCategory(isActive: true, name: 'credit and debit notes', type:'category14', ),
    SubCategory(isActive: true, name: 'Bill of supply', type:'category14', ),
    SubCategory(isActive: true, name: 'Recipient Voucher', type:'category14', ),
    SubCategory(isActive: true, name: 'Refund Voucher', type:'category14', ),
    SubCategory(isActive: true, name: 'Payment Voucher', type:'category14', ),
    SubCategory(isActive: true, name: 'E-way bill', type:'category14', ),
  ]),
  CategoryModel(isActive: true, name: 'Debit And Credit Notes', type: 'category15',subcategory: null),
  CategoryModel(isActive: true, name: 'Account And Records', type: 'category16',subcategory: [
    SubCategory(isActive: true, name: 'Accounts and other records', type:'category16', ),
    SubCategory(isActive: true, name: 'Period of retention', type:'category16', ),
  ]),
  CategoryModel(isActive: true, name: 'Returns', type: 'category17',subcategory: [
    SubCategory(isActive: true, name: 'Furnishing outward supplies', type:'category17', ),
    SubCategory(isActive: true, name: 'Furnishing inward supplies', type:'category17', ),
    SubCategory(isActive: true, name: 'Furnishing returns', type:'category17', ),
    SubCategory(isActive: true, name: 'first return', type:'category17', ),
    SubCategory(isActive: true, name: 'claim of ITC & provisional acceptance thereof', type:'category17', ),
    SubCategory(isActive: true, name: 'ITC-Matching,Reversal and Reclaim', type:'category17', ),
    SubCategory(isActive: true, name: 'Reduction of output tax liability', type:'category17', ),
    SubCategory(isActive: true, name: 'Procedure-furnishing returns', type:'category17', ),
    SubCategory(isActive: true, name: 'annual return', type:'category17', ),
    SubCategory(isActive: true, name: 'final return', type:'category17', ),
    SubCategory(isActive: true, name: 'notice to defaulters', type:'category17', ),
    SubCategory(isActive: true, name: 'levy-Late fee', type:'category17', ),
    SubCategory(isActive: true, name: 'GST practioner', type:'category17', ),
  ]),
  CategoryModel(isActive: true, name: 'Gst Practitioner', type: 'category18',subcategory: null),
  CategoryModel(isActive: true, name: 'Payment Of Tax', type: 'category19',subcategory:[
    SubCategory(isActive: true, name: 'Utilisation of ITC (Subjected to conditions)', type:'category19', ),
    SubCategory(isActive: true, name: 'Order of ITC Utilisation', type:'category19', ),
    SubCategory(isActive: true, name: 'Interest - delayed payment', type:'category19', ),
    SubCategory(isActive: true, name: 'TDS', type:'category19', ),
    SubCategory(isActive: true, name: 'TCS', type:'category19', ),
    SubCategory(isActive: true, name: 'Transfer of ITC', type:'category19', ),
    SubCategory(isActive: true, name: 'Transfer - Certain Amounts', type:'category19', ),
    SubCategory(isActive: true, name: 'Electronic Liability Register', type:'category19', ),
    SubCategory(isActive: true, name: 'Electronic Credit Ledger', type:'category19', ),
    SubCategory(isActive: true, name: 'Electronic Cash Ledger.', type:'category19', ),
    
  ] ),
  CategoryModel(isActive: true, name: 'Tax Deduction At Source', type: 'category20',subcategory:null ),
  CategoryModel(isActive: true, name: 'Refunds', type: 'category21',subcategory:[
    SubCategory(isActive: true, name: 'Refund - Tax', type:'category21', ),
    SubCategory(isActive: true, name: 'Refund - Certain Cases', type:'category21', ),
    SubCategory(isActive: true, name: 'Interest - Delayed Refund', type:'category21', ),
    SubCategory(isActive: true, name: 'Consumer welfare fund', type:'category21', ),
    SubCategory(isActive: true, name: 'Utilisation of Fund', type:'category21', ),
    SubCategory(isActive: true, name: 'Manual filing and processing', type:'category21', ),
  ]),
  CategoryModel(isActive: true,name: 'Assessment', type: 'category22',subcategory:[
    SubCategory(isActive: true, name: 'Self-Assesment', type:'category22', ),
    SubCategory(isActive: true, name: 'Provisional Assessment', type:'category22', ),
    SubCategory(isActive: true, name: 'Scrutiny of Returns', type:'category22', ),
    SubCategory(isActive: true, name: 'Non-filers of return', type:'category22', ),
    SubCategory(isActive: true, name: 'Assessment - Unregd. Person', type:'category22', ),
    SubCategory(isActive: true, name: 'Summary Assessment', type:'category22', ),
  ]),
  CategoryModel(isActive: true,name: 'Audit', type: 'category23',subcategory:[
    SubCategory(isActive: true, name: 'Audit- Tax Authorities', type:'category23', ),
    SubCategory(isActive: true, name: 'Special Audit', type:'category23', ),
    
  ]),
  CategoryModel(isActive: true,name: 'Inspection, Search, Seisure and Arrest', type: 'category24',subcategory:[
    SubCategory(isActive: true, name: 'Power of Inspection, Search, Seizure', type:'category24', ),
    SubCategory(isActive: true, name: 'Inspection- Goods in Movement', type:'category24', ),
    SubCategory(isActive: true, name: 'Power to Arrest', type:'category24', ),
    SubCategory(isActive: true, name: 'Power to Summon person for evidence and documents', type:'category24', ),
    SubCategory(isActive: true, name: 'Access to Business premises', type:'category24', ),
    SubCategory(isActive: true, name: 'Officers to Assist P.O.', type:'category24', ),
  ]),
  CategoryModel(isActive: true, name: 'Demand And Recovery', type: 'category25',subcategory:[
    SubCategory(isActive: true, name: 'Supression of facts - other than fraud.', type:'category25', ),
    SubCategory(isActive: true, name: 'Supression of facts - Due to fraud and wilfully.', type:'category25', ),
    SubCategory(isActive: true, name: 'General Provisions - Determination of Tax', type:'category25', ),
    SubCategory(isActive: true, name: 'Tax Collected but not paid', type:'category25', ),
    SubCategory(isActive: true, name: 'Tax wrongfully collected and paid', type:'category25', ),
    SubCategory(isActive: true, name: 'Inititiation - Recovery proceedings', type:'category25', ),
    SubCategory(isActive: true, name: 'Recovery of Tax', type:'category25', ),
    SubCategory(isActive: true, name: 'Payment in Installments', type:'category25', ),
    SubCategory(isActive: true, name: 'Transfer of property - Void in certain cases', type:'category25', ),
    SubCategory(isActive: true, name: 'Tax - First charge on property', type:'category25', ),
    SubCategory(isActive: true, name: 'Provisional Attachment to protect revenue', type:'category25', ),
    SubCategory(isActive: true, name: 'Continuation and Validation of Recovery proceedings.', type:'category25', ),
 
  ]),
  CategoryModel(isActive: true, name: 'Advance Ruling', type: 'category26',subcategory:[
    SubCategory(isActive: true, name: 'Definitions', type:'category26', ),
    SubCategory(isActive: true, name: 'Authority', type:'category26', ),
    SubCategory(isActive: true, name: 'Application', type:'category26', ),
    SubCategory(isActive: true, name: 'Procedure', type:'category26', ),
    SubCategory(isActive: true, name: 'Appellate Authority', type:'category26', ),
    SubCategory(isActive: true, name: 'Appeal to Appellate Authority', type:'category26', ),
    SubCategory(isActive: true, name: 'Order of Appellate Authority', type:'category26', ),
    SubCategory(isActive: true, name: 'National Appellate Authority (NAA) -Constitution', type:'category26', ),
    SubCategory(isActive: true, name: 'National Appellate Authority (NAA)- Appeals', type:'category26', ),
    SubCategory(isActive: true, name: 'National Appellate Authority (NAA)- Order', type:'category26', ),
    SubCategory(isActive: true, name: 'Rectification', type:'category26', ),
    SubCategory(isActive: true, name: 'Applicability', type:'category26', ),
    SubCategory(isActive: true, name: 'Void in certain cases', type:'category26', ),
    SubCategory(isActive: true, name: 'Powers of Authority, Appellate Authority and NAA', type:'category26', ),
    SubCategory(isActive: true, name: 'Procedure - Authority, Appellate Authority and NAA', type:'category26', ),
 
  ]),
  CategoryModel(isActive: true, name: 'Appeals And Revision', type: 'category27',subcategory:[
     SubCategory(isActive: true, name: 'Appeals', type:'category27', ),
    SubCategory(isActive: true, name: 'Powers - Revisional Authority', type:'category27' ),
    SubCategory(isActive: true, name: 'Constitution - Appellate Tribunal and Benches', type:'category27', ),
     SubCategory(isActive: true, name: 'President and Members - Appeallate Tribunal', type:'category27', ),
    SubCategory(isActive: true, name: 'Procedure - Appellate Tribunal', type:'category27' ),
    SubCategory(isActive: true, name: 'Appeals -  Appellate Tribunal', type:'category27', ),
    SubCategory(isActive: true, name: 'Orders of Appellate Tribunal', type:'category27', ),
    SubCategory(isActive: true, name: 'President - Financial and Administrative Powers', type:'category27' ),
    SubCategory(isActive: true, name: 'Interest on refund - Amount paid for admission of appeal', type:'category27', ),
     SubCategory(isActive: true, name: 'Appeal - High Court', type:'category27', ),
    SubCategory(isActive: true, name: 'Appeal - Supreme Court', type:'category27' ),
    SubCategory(isActive: true, name: 'Sums due to be paid', type:'category27', ),
    SubCategory(isActive: true, name: 'Appeal not to filed', type:'category27' ),
    SubCategory(isActive: true, name: 'Non-Appealable decisions and orders', type:'category27', ),
  ]),
  CategoryModel(isActive: true,name: 'Offenses And Penalty', type: 'category28',subcategory:null),
  CategoryModel(isActive: true,name: 'Transitional Provisions', type: 'category29',subcategory:null),
   CategoryModel(isActive: true,name: 'Job Work Procedure', type: 'category30',subcategory:null),
  CategoryModel(isActive: true,name: 'Common Portal', type: 'category31',subcategory:null),
  CategoryModel(isActive: true, name: 'Deemed Exports', type: 'category32',subcategory:null),
  CategoryModel(isActive: true, name: 'Gst Complaince Rating', type: 'category33',subcategory:null),
  CategoryModel(isActive: true,name: 'Anti-Profiteering Measure', type: 'category34',subcategory:null),
 
];